services:
  mysql:
    image: mysql:8.0
    container_name: kernelLetter-mysql
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 12345678
      MYSQL_DATABASE: kernelLetter
      TZ: Asia/Seoul
    volumes:
      - kernelLetter-mysql-data:/var/lib/mysql
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p12345678"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  kernelLetter-mysql-data:
    driver: local
